sudo: required
services:
  - docker

before_install:
  - docker build -t thabizolo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thabizolo/react-test npm test -- --coverage
  
after_success:
  - docker build -t thabizolo/multi-client ./client
  - docker build -t thabizolo/multi-nginx ./nginx
  - docker build -t thabizolo/multi-server ./server
  - docker build -t thabizolo/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take images and push them to Docker hub
  - docker push thabizolo/multi-client
  - docker push thabizolo/multi-nginx
  - docker push thabizolo/multi-server
  - docker push thabizolo/multi-worker


